# works with vscode-extension: humao.rest-client
GET http://localhost:3001

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "john3",
    "email": "johndoe@gmail.com",
    "password": "wcwojwfwicj"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "john3",
    "password": "wcwojwfwicj"
}


###
GET http://localhost:3001/users?currPage=1