# works with vscode-extension: humao.rest-client
GET http://localhost:3001

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "john3",
    "email": "johndoe@gmail.com",
    "password": "wcwojwfwicj"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "john3",
    "password": "wcwojwfwicj"
}


###
GET http://localhost:3001/users?currPage=1



###
POST http://localhost:3001/send_msg
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDc1NjM1NzUsInVzZXJuYW1lIjoiam9objMifQ.avXy0s6gaspiwAYRDUT4VOKPRid6v4LXtrRTe2cltoU

{
   "to": "john2",
    "message": "hello, john!"
}


###
GET http://localhost:3001/get_msgs?to=john2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDc1NjM1NzUsInVzZXJuYW1lIjoiam9objMifQ.avXy0s6gaspiwAYRDUT4VOKPRid6v4LXtrRTe2cltoU

